# Generated by Django 6.0.3 on 2026-03-13 13:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('organs', models.JSONField(default=list, help_text='List of organs willing to donate')),
                ('medical_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Matched', 'Matched'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('organ_needed', models.CharField(choices=[('Kidney', 'Kidney'), ('Liver', 'Liver'), ('Heart', 'Heart'), ('Lungs', 'Lungs'), ('Pancreas', 'Pancreas'), ('Intestine', 'Intestine'), ('Corneas', 'Corneas'), ('Bone Marrow', 'Bone Marrow'), ('Skin', 'Skin')], max_length=20)),
                ('urgency', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=10)),
                ('medical_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Matched', 'Matched'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ', models.CharField(choices=[('Kidney', 'Kidney'), ('Liver', 'Liver'), ('Heart', 'Heart'), ('Lungs', 'Lungs'), ('Pancreas', 'Pancreas'), ('Intestine', 'Intestine'), ('Corneas', 'Corneas'), ('Bone Marrow', 'Bone Marrow'), ('Skin', 'Skin')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('matched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='registry.donor')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='registry.recipient')),
            ],
            options={
                'ordering': ['-matched_at'],
                'unique_together': {('donor', 'recipient', 'organ')},
            },
        ),
    ]
