services:
  - type: web
    name: organ-donation-system
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput && chmod +x start.sh
    startCommand: ./start.sh
    envVars:
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: 3.11.12
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: "8000"
